export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const BUSCAR_POR_ASCENDENTE = "BUSCAR_POR_ASCENDENTE";
export const BUSCAR_POR_DESCENDENTE = "BUSCAR_POR_DESCENDENTE";
export const BUSCAR_POR_CONDICION_NEW = "BUSCAR_POR_CONDICION_NEW";
export const BUSCAR_POR_CONDICION_USED = "BUSCAR_POR_CONDICION_USED";